### ISSUE TITLE
Can source and receiver don't locate on grid lines?

### ISSUE THREAD

**Issue by xichaoqiang** [kevinganster/eikonalfm#4]
Hello  I am very interested in you program.

I have a question.

Can source and receiver don't locate on grid lines?

**Comment by kevinganster** [comment]
No, the source position has to coincide with the grid.

If it's not, maybe one could interpolate the values at the 4 grid-points surrounding the source and set the known values there as start values for the algorithm (the eikonal equation needs a boundary/initial condition). You would have to think about how exactly those have to be calculated in this case. Also, you would need to implement the interface to initialize a set of points as the known set (instead of just the source position). The last part is not very hard in principle, but i wont add it to my own implementation.

The simpler options are to either:
- round the source position to the nearest gridpoint. If the mesh is fine enough the error should be rather small.
- align the mesh, so that the source position is also a grid-position

Does this answer your question?

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
Another eikonal solver is suit for the condition which source and receiver are not on grid line.
But the sensitivity is ray raytrcing.
https://github.com/keurfonluu/fteikpy

**Comment by kevinganster** [comment]
If you look into their code you'll see that they do exactly what i said earlier, they simply convert the real source position into a grid position by rounding accordingly, or initialize the 4 surrounding grid points: [See this file](https://github.com/keurfonluu/fteikpy/blob/b2c22edeee287791eb7413f1424aa9ccb5da60dd/fteikpy/_fteik/_fteik2d.py#L291)

(zsrc, xsrc) is the actual source position
```python
# Convert src to grid position and try and take into account machine precision
zsa = zsrc / dz
xsa = xsrc / dx

# Try to handle edges simply for source due to precision
zsa = zsa - eps if zsa >= nz else zsa
xsa = xsa - eps if xsa >= nx else xsa

# Grid points to initialize source
zsi = min(int(zsa), nz - 1)
xsi = min(int(xsa), nx - 1)

...
```
Then they do some checks whether the source is close enough to a grid point. If yes, they simply round to the gridpoint. If not they calculate an analytical time in the function `t_anad` for the 4 surrounding grid points

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
Your reply is very useful.

**Comment by xichaoqiang** [comment]
This method is indeed more accurate and practical. Because in practical applications the source and receiver are often not on the grid. Reducing the mesh size can improve the accuracy but also increase the computational cost.

**Comment by kevinganster** [comment]
You are probably right.

But if i wanted to incorporate this into my software, i would have to change a few things. For example: setting the starting values of tau/tau1, the C++ part would also need to  calculate the analytical solutions, and probably some things i forgot.
If i see it right, the "analytical solution" for the 4 surrounding grid-points is calculated by assuming constant velocity and multiplying the inverse velocity with the distance to the off-grid source, which would be the solution in the constant case.

Since i don't need off-grid sources in my applications, i don't see the benefit (at the moment) of trying to implement this into the scheme. I hope you can understand that and sorry to disappoint you.

But you are very welcome to open up a pull request and propose an implementation for the analytical initialization.
